release-please:
  branches:
    - main
  changelog-types:
    - type: feat
      section: Features
    - type: fix
      section: Bug Fixes
    - type: docs
      section: Documentation
    - type: chore
      section: Chores
    - type: refactor
      section: Refactors
